version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004/202010-01
    resource_class: nguyendt456/popos-server
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - go-mod-v4-{{ checksum "go.sum" }}
      # - run:
      #     name: Install Dependencies
      #     command: go get ./...
      # - save_cache:
      #     key: go-mod-v4-{{ checksum "go.sum" }}
      #     paths:
      #       - "/go/pkg/mod"
      # - run:
      #     name: Replace variable
      #     command: ./test/replace_credentials.sh
      # - run:
      #     name: Run tests
      #     command: go test -v ./test
      - run:
          name: Build and tag image 
          command: | 
            docker build . -t dynamic-dns-service:latest
            docker tag dynamic-dns-service:latest registry.binhnguyen.dev/public_project/dynamic-dns-service
      - run:
          name: Login to docker registry
          command: echo $REGISTRY_PASS | docker login --username $REGISTRY_USER --password-stdin
      - run:
          name: Push image
          command: docker push registry.binhnguyen.dev/public_project/dynamic-dns-service
